
const ActionTypes = {
    USERNAME:'USERNAME',
    EMAIL:"EMAIL",
    PASSWORD:"PASSWORD",
    CURRENTUSER:'CURRENTUSER',
    ALLUSERS:'ALLUSERS',
    MESSAGES: 'MESSAGES',
    CHANGERECPUID: 'CHANGERECPUID',
    RENDERTODOS: 'RENDERTODOS',
    ADDTODO:"ADDTODO",
}

export default ActionTypes;